- name: copy repo file
  copy: src=mongodb.repo dest=/etc/yum.repos.d/mongodb.repo mode=0644
  sudo: yes

- name: install mongodb
  yum: name=mongodb-org state=present
  sudo: yes

- name: start mongo
  service: name=mongod state=started enabled=yes
  sudo: yes
